// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oohqsyawrdwddjmcenes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vaHFzeWF3cmR3ZGRqbWNlbmVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyMDg5MTUsImV4cCI6MjA4Njc4NDkxNX0.Y537aENc_-ISSNEyW3pDr8ximqADeCsLL8S3tJasbsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});